[WIP] Filter typing
geostyler/geostyler-style pull request #156
Opened 2021-03-17 10:48 UTC by KaiVolland

2021-03-17 20:07 UTC, marcjansen reviewed
Looks fine to my eyes, but this shouldn't be considered a proper review.

2021-03-18 08:15 UTC, jansule requested changes

2021-03-18 08:15 UTC, jansule commented on schema.json
> +            "description": "A CombinationFilter combines N Filters with a logical OR / AND operator.\n\nThis is just type secure for a maximum of 10 combined filters as you can't\ntype 'rest' paramet
the maximum of 10 filters does not apply anymore, right?

2021-03-18 08:15 UTC, jansule commented on schema.json
> +                    "description": "The possible Operator used for combination Filters.",
```suggestion
                    "description": "The possible Operators used for combination Filters.",
```

2021-03-18 08:15 UTC, jansule commented on schema.json
> +                    "description": "A FunctionFilter that expects a string (propertyName) as second arguement and\na regular expression as third argument. An actual parser implementation has to\nretu
```suggestion
                    "description": "A FunctionFilter that expects a string (propertyName) as second argument and\na regular expression as third argument. An actual parser implementation has to\nreturn a value for this function expression.",
```

2021-03-18 08:15 UTC, jansule commented on schema.json
> +                                    "description": "A FunctionFilter that expects a string (propertyName) as second arguement and\na regular expression as third argument. An actual parser implementat
```suggestion
                                    "description": "A FunctionFilter that expects a string (propertyName) as second argument and\na regular expression as third argument. An actual parser implementation has to\nreturn a value for this function expression.",
```

2021-03-18 08:27 UTC, jansule approved these changes
Very nice!

2021-03-18 08:58 UTC, dnlkoch approved these changes

2021-03-18 08:58 UTC, dnlkoch commented on index.d.ts
> +export type PropertyValue = string|number|boolean|null;
```suggestion
export type PropertyValue = string | number | boolean | null;
```

2021-03-18 09:26 UTC, merged