TypeGuards
geostyler/geostyler-style pull request #161
Opened 2021-03-26 12:22 UTC by KaiVolland

This introduces some custom [TypeGuards](https://basarat.gitbook.io/typescript/type-system/typeguard#user-defined-type-guards) to enhance check for specific types.

When used the TypeGuards enhance the typing and implicit the readability of the code.
Many `as Filter` occurences can be omited in the parsers though.

Compare `examples/typeguardsample.ts ` for more details.

2021-03-26 13:11 UTC, simonseyock reviewed
This looks very useful! I think some checks could be a little bit extended, but I am especially not sure about the array lengths.

2021-03-26 13:11 UTC, simonseyock commented on typeguards.ts
> +  return got.kind === 'Line';
```suggestion
  return hasKind(got) && got.kind === 'Line';
```

2021-03-26 13:11 UTC, simonseyock commented on typeguards.ts
> +  return got.kind === 'Fill';
```suggestion
  return hasKind(got) && got.kind === 'Fill';
```

2021-03-26 13:11 UTC, simonseyock commented on typeguards.ts
> +  return got.kind === 'Raster';
```suggestion
  return hasKind(got) && got.kind === 'Raster';
```

2021-03-26 13:11 UTC, simonseyock commented on typeguards.ts
> +  return _isString(got.name) &&
```suggestion
  return _isObject(got) &&
    _isString(got.name) &&
```

2021-03-26 13:11 UTC, simonseyock commented on typeguards.ts
> +    !got.symbolizers.some((arg: any) => !isSymbolizer(arg)); // does not contain anything that is not a symbolizer
```suggestion
    got.symbolizers.every((arg: any) => isSymbolizer(arg));
```

2021-03-26 13:11 UTC, simonseyock commented on typeguards.ts
> +import _isRegExp from 'lodash/isRegExp';
```suggestion
import _isRegExp from 'lodash/isRegExp';
import _isObject from 'lodash/isObject';
```

2021-03-26 13:15 UTC, simonseyock commented on typeguards.ts
> +// Symbolizers
maybe it makes everything a little more compact to just use `_isObject(got)` instead of `hasKind(got)`

2021-03-29 06:59 UTC, KaiVolland commented on typeguards.ts
> +  return (got.min || got.max) &&
I think this is not needed as `got.min` and `got.max` would be `undefined` (falsy) if `got` would be a string, array, number, boolean.

2021-03-29 07:07 UTC, KaiVolland commented
Thanks for the review. I skipped the `_isObject` checks as just level 1 properties are accessed which should result in `undefined`.

2021-03-29 07:23 UTC, simonseyock commented on typeguards.ts
> +  return (got.min || got.max) &&
True, but it would still fail if it was `undefined` or `null`.

2021-03-29 07:26 UTC, KaiVolland commented on typeguards.ts
> +  return (got.min || got.max) &&
I'll add `?.`

2021-03-29 08:39 UTC, dnlkoch approved these changes

2021-03-29 08:40 UTC, simonseyock commented on typeguards.ts
> +    (got?.filter ? isFilter(got.filter) : true) &&
The `?` should be in the first line -> `_isString(got?.name)`

2021-03-29 08:41 UTC, simonseyock commented on typeguards.ts
>    return ['Icon', 'Text', 'Mark'].includes(got.kind);
here a `?` is missing

2021-03-29 08:49 UTC, jansule requested changes

2021-03-29 08:49 UTC, jansule commented on examples/typeguardsample.ts
> +const combinationOpertor: any = '&&';
```suggestion
const combinationOperator: any = '&&';
```

2021-03-29 08:49 UTC, jansule commented on examples/typeguardsample.ts
> +  console.log(`${combinationOpertor} is an Operator`);
```suggestion
  console.log(`${combinationOperator} is an Operator`);
```

2021-03-29 08:49 UTC, jansule commented on examples/typeguardsample.ts
> +if (isCombinationOperator(combinationOpertor)) {
```suggestion
if (isCombinationOperator(combinationOperator)) {
```

2021-03-29 08:49 UTC, jansule commented on examples/typeguardsample.ts
> +  console.log(`${combinationOpertor} is a CombinationOperator`);
```suggestion
  console.log(`${combinationOperator} is a CombinationOperator`);
```

2021-03-29 08:49 UTC, jansule commented on examples/typeguardsample.ts
> +if (isNegationOpeartor(negationOperator)) {
```suggestion
if (isNegationOperator(negationOperator)) {
```

2021-03-29 08:49 UTC, jansule commented on typeguards.ts
> +    isNegationOpeartor(got);
```suggestion
    isNegationOperator(got);
```

2021-03-29 08:52 UTC, jansule approved these changes
Very nice!

2021-03-29 08:54 UTC, simonseyock approved these changes

2021-03-29 09:03 UTC, merged